Create mock weight class
zotbins/ZotbinsCore pull request #20
Opened 2022-04-28 23:28 UTC by limenilbuz

## Description

Created the Mock Weight class that inherits from the IWeight class. Only have two member functions so far, the constructor, and the getWeight() overridden function.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code improvement (a non-breaking change that improves the quality of the code)
- [ ] Documentation Change (update to the documentation with no changes to the code)

## Testing and Verification Instructions

1. Build using the default environment
2. Verify that the build compiles successfully and that only the debug environment is built

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2022-04-28 23:46 UTC, patrickanguyen requested changes
I requested some changes.

Also, some other things

- Your commit message for co-author isn't correct. It should be this (notice the <> and no <<, I mentioned on Slack that it was a placeholder for whitespace).
```


Co-authored by: Derek Skinner <60554721+dskin344@users.noreply.github.com>
```
- Check one of the `Type of Change`
- Update the `Testing and Verification` Instructions
- Mark all of the options in `Checklist` - You did that part that you didn't check mark

2022-04-28 23:46 UTC, patrickanguyen commented on lib/Weight/MockWeight.hpp
> +class MockWeight : IWeight
Mark the class as `final`, so classes can't inherit from `MockWeight` and make it a public inheritance.

2022-04-28 23:46 UTC, patrickanguyen commented on lib/Weight/MockWeight.hpp
> +    MockWeight(int32_t mWeight);
Change `mWeight` to `weight` because the `mWeight` in the parameters is not a member variable

2022-04-28 23:46 UTC, patrickanguyen commented on lib/Weight/MockWeight.hpp
> +     * @return int32_t
Mention that int32_t returns weight in kilograms

2022-04-28 23:46 UTC, patrickanguyen commented on lib/Weight/MockWeight.hpp
> +
Remove whitespace at line 8, so it's more clear that the comment belongs to the class

2022-04-28 23:53 UTC, limenilbuz commented
What do you mean by "Update the Testing and Verification Instructions"?

2022-04-29 00:28 UTC, patrickanguyen commented
Oops, my bad it should be 
```


Co-authored-by: Derek Skinner <60554721+dskin344@users.noreply.github.com>
```

2022-04-29 00:45 UTC, patrickanguyen commented on lib/Weight/MockWeight.hpp
> +     * @return int32_t
Remove the `in kilograms` on line 19. It should be on line 20, so 
```
@return int32_t Weight in kilograms
```

2022-05-03 00:18 UTC, sagarbpatel31 approved these changes

2022-05-05 19:23 UTC, limenilbuz commented
> Update this ![image](https://user-images.githubusercontent.com/41417417/165868213-91fde2c0-940c-460d-9ae2-a5d0ea72efd6.png)

I'm still not sure what I should change about this, but we can go over it in the meeting!

2022-05-05 23:05 UTC, closed without merging