Create unit tests for fullness
zotbins/ZotbinsCore pull request #42
Opened 2022-05-12 22:46 UTC by aahsue

## Description

Created unit tests using the Mock Distance Sensor and the Fullness Class. Checked if mock distance sensor can be constructed, that it returns the correct distance, that it can loop through the distances, and that the Fullness class returns the correct fullness and if it can recognize if a distance is valid.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code improvement (a non-breaking change that improves the quality of the code)
- [ ] Documentation Change (update to the documentation with no changes to the code)

## Testing and Verification Instructions

1. Build and compile and there are no errors
2. Run the unit tests and they all pass

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-05-17 01:10 UTC, patrickanguyen requested changes
More meaningful tests needed to be added in the future, but we can just merge this once these changes are made

2022-05-17 01:10 UTC, patrickanguyen commented on test/test_desktop_fullness/testFullness.cpp
> +}
remove

2022-05-17 01:10 UTC, patrickanguyen commented on test/test_desktop_fullness/testFullness.cpp
> +    int32_t calculatedAverageDistance = 5; // should be 5.5
this should be a float

2022-05-17 01:10 UTC, patrickanguyen commented on test/test_desktop_fullness/testFullness.cpp
> +    TEST_ASSERT_EQUAL_INT(calculatedAverageDistance, (mockFullness.getFullness()));
getFullness() returns a float

2022-05-17 01:10 UTC, patrickanguyen commented on test/test_desktop_fullness/testFullness.cpp
> +    int32_t calculatedAverageDistance = 5; // should be 5.5
Make these const

2022-05-19 06:12 UTC, limenilbuz commented
lgtm

2022-05-19 18:51 UTC, sagarbpatel31 reviewed
Lgtm now

2022-05-19 22:10 UTC, patrickanguyen approved these changes

2022-05-19 22:10 UTC, merged