Implemented Ultrasonic Sensor
zotbins/ZotbinsCore pull request #43
Opened 2022-05-25 02:04 UTC by aahsue

## Description

Interfaced fullness class with ultrasonic sensor and ESP-32 .

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code improvement (a non-breaking change that improves the quality of the code)
- [ ] Documentation Change (update to the documentation with no changes to the code)

## Testing and Verification Instructions

1. Wire ESP-32 and ultrasonic sensor (trig pin 5, echo pin 18)
2. Build
3. Upload
4. Open serial monitor

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-05-25 02:41 UTC, patrickanguyen requested changes

2022-05-25 02:41 UTC, patrickanguyen commented on src/fullnessTask.cpp
> +            digitalWrite(trigPin, LOW);
Add all of the library code to a new class called `UltrasonicDistance` that inherits from IDistance

2022-05-25 02:41 UTC, patrickanguyen commented on src/fullnessTask.cpp
> +int amount = 0;
Does not need to be in global scope. Move to loop()

2022-05-25 02:41 UTC, patrickanguyen commented on src/fullnessTask.cpp
> +std::vector<int32_t> distances;
Change to std::array because std::vector uses the heap

2022-05-25 02:41 UTC, patrickanguyen commented on src/fullnessTask.cpp
> +        // log_i();
Remove

2022-05-25 19:37 UTC, dskin344 approved these changes
🤝

2022-06-02 21:50 UTC, patrickanguyen requested changes

2022-06-02 21:50 UTC, patrickanguyen commented on lib/Fullness/UltrasonicDistance.cpp
> +}
Remove startDistance(). Just call 8 times in getDistance()

2022-06-02 21:50 UTC, patrickanguyen commented on src/fullnessTask.cpp
> +#include "MockDistance.hpp"
Remove this - this is only for unit tests

2022-06-02 21:50 UTC, patrickanguyen commented on src/fullnessTask.cpp
> +#include <vector>
Remove this

2022-06-02 21:50 UTC, patrickanguyen commented on src/fullnessTask.cpp
> +    Serial.begin(115200);
Remove this

2022-06-02 21:50 UTC, patrickanguyen commented on src/fullnessTask.cpp
> +        Fullness::UltrasonicDistance ultrasonicSensor(trigPin, echoPin, 0);
Make ultrasonicDistance and FullnessMetric a member variable

2024-11-21 19:48 UTC, closed without merging