Oscar + Jerald PR breakbeam sensor
zotbins/ZotbinsCore pull request #55
Opened 2024-12-03 22:32 UTC by pfsnubs

## Description

Please write description of change

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code improvement (a non-breaking change that improves the quality of the code)
- [ ] Documentation Change (update to the documentation with no changes to the code)

## Testing and Verification Instructions

1. Step 1
2. Step 2

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-12-04 01:36 UTC, alxkeda requested changes

2024-12-04 01:36 UTC, alxkeda commented on components/UsageComponent/include/task.hpp
there is a way for usage component to have access to task component and thus the header files in the include. i believe you just need to add the component names in the REQUIRES field in the cmake file. i would do this before we merge to maintain the separation of rtos task stuff and our own components

2024-12-04 01:36 UTC, alxkeda commented on components/UsageComponent/CMakeLists.txt
> +		    REQUIRES driver esp_timer)
```suggestion
		    REQUIRES driver esp_timer TaskComponent)
```

2024-12-04 01:36 UTC, alxkeda commented on components/UsageComponent/CMakeLists.txt
> +		    REQUIRES driver esp_timer)
try this

2024-12-04 01:36 UTC, alxkeda commented on components/UsageComponent/include/usageTask.hpp
see my other comments about the cmake stuff :)

2024-12-04 01:36 UTC, alxkeda commented on components/TaskComponent/usageTask.cpp
i see you've also added a definition for this pin in the zotbins namespace, i actually think this is the style we should move towards so if any pin assignments are overlapping we'll get an error cos of the scope (a redefinition of a constant). if you define it like this you also don't need it in this file so that would be nice and then we can just add a comment or something on the first usage of the pin as a reminder in the file itself

2024-12-04 01:36 UTC, alxkeda commented on components/UsageComponent/include/usageTask.hpp
> +        gpio_num_t DETECT_PIN = GPIO_NUM_16;
```suggestion
        const gpio_num_t DETECT_PIN = GPIO_NUM_16;
```

2024-12-04 01:36 UTC, alxkeda commented on components/UsageComponent/usageTask.cpp
see my other comments about the cmake stuff :)

2024-12-04 01:36 UTC, alxkeda commented on dependencies.lock
we should probably add this to the gitignore so ppl dont have to keep changing the paths, or at least add a comment if we want to keep it for version info

2024-12-07 00:57 UTC, pfsnubs commented on .vscode/settings.json
I'm also gonna add this to the gitignore since the port will change across users

2025-09-16 20:09 UTC, closed without merging